### ISSUE TITLE
Build and include DwarFS statically

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/tebako#2]
Thanks to @mhx the author of DwarFS he has given us a great tip on how to build DwarFS statically:

https://github.com/mhx/dwarfs/blob/main/cmake/static_link.sh

**Comment by ronaldtse** [comment]
Let's use CMake to build Tebako, as well.

**Comment by maxirmx** [comment]
I pushed a version that  includes and builds DwarFS statically using CMake and GHA.
Unfortunately such static build that reimplements the tip from https://github.com/mhx/dwarfs/blob/main/cmake/static_link.sh does not work and, frankly speaking, it cannot work.

The author himself does not use it.
In https://github.com/mhx/dwarfs/blob/main/CMakeLists.txt this type of build is quarded with condition if(STATIC_BUILD_DO_NOT_USE) which looks like a very clear sign.

The issue with the approach to static link suggested at https://github.com/mhx/dwarfs/blob/main/cmake/static_link.sh / https://github.com/mhx/dwarfs/blob/main/CMakeLists.txt is that some of the static libraries listed are linked against static gcc run-time and some are linked against shared gcc run-time and all together makes libdl crazy.

I am not sure that it can be fixed for folly since it is not designed to be flexible. Actually it is designed to be unflexible :)
I am still pushing this implementation to master just to have some baseline for further development.


There are too possible options to proceed:
- implement a build as the author really does it in his CMake configuration (recommended)
- fix problems with static builds.  Some of them can be definitly fixed (for example, static Boost libs linked against static run-time)  but some of them may be real blockers (some folly features)

**Comment by ronaldtse** [comment]
> The author himself does not use it.
> In https://github.com/mhx/dwarfs/blob/main/CMakeLists.txt this type of build is guarded with condition if(STATIC_BUILD_DO_NOT_USE) which looks like a very clear sign.

https://github.com/mhx/dwarfs/blob/2a51edb67b7683be6c175f65558fab36fe20ec24/CMakeLists.txt#L37
```cmake
option(STATIC_BUILD_DO_NOT_USE "try static build (experimental)" OFF)
```
Just says it's experimental. 

The author has privately communicated that this usage can be supported, that's why we were provided with the guidance on how to perform a static build.

> * implement a build as the author really does it in his CMake configuration (recommended)

This seems reasonable, do you foresee any issue? The key is that the resulting tebako binary needs to be standalone (static).

**Comment by maxirmx** [comment]
If resulting tebako binary needs to be standalone it requires statis build. Hopefully I can reduce to the set of libraries and utilities that we need.

**Comment by maxirmx** [comment]
https://github.com/mhx/dwarfs/issues/54

This is not a blocker, we can just exclude this application from tebaco build

**Comment by ronaldtse** [comment]
@maxirmx we can certainly exclude the application `dwarfsextract` but the tebako-generated binary output needs to be able to utilize the FS in the image.
